// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlS0eGl_F6eUF12Tv-3H4f9W6AOJi-l_g',
    appId: '1:805251626890:web:4044ddd045ab2f255dba73',
    messagingSenderId: '805251626890',
    projectId: 'carpoolapp-6b72e',
    authDomain: 'carpoolapp-6b72e.firebaseapp.com',
    storageBucket: 'carpoolapp-6b72e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT2vcwUtXCaosTi1bWI-oEb5VGPuq3N_8',
    appId: '1:805251626890:android:528c4e30fb9319865dba73',
    messagingSenderId: '805251626890',
    projectId: 'carpoolapp-6b72e',
    storageBucket: 'carpoolapp-6b72e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHCIvCHJzPMYxOYCZArmAsOkBdS_3Wazg',
    appId: '1:805251626890:ios:1d4c9cd3bf5320c05dba73',
    messagingSenderId: '805251626890',
    projectId: 'carpoolapp-6b72e',
    storageBucket: 'carpoolapp-6b72e.appspot.com',
    iosBundleId: 'com.example.carpoolapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHCIvCHJzPMYxOYCZArmAsOkBdS_3Wazg',
    appId: '1:805251626890:ios:fbfac6e48dc713ed5dba73',
    messagingSenderId: '805251626890',
    projectId: 'carpoolapp-6b72e',
    storageBucket: 'carpoolapp-6b72e.appspot.com',
    iosBundleId: 'com.example.carpoolapp.RunnerTests',
  );
}
